# Basic
title: 沉浸书房
subtitle: 书匣子
description: SecondTech的官方记录匣子
# 头像里面的标题
avatarTitle: SecondTech
# 头像里面的描述
avatarDesc: 概述/更新记录
url: "http://www.baidu.com"

# Comment
comment:
    #disqus: leopard
    # gitment: xxx // 需要修改 comments.html中的client_id和client_secret
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    #weibo: 5366874726
    github: caishangqi
    # zhihu: panpanleopard
    # juejin: xxx
    #jianshu: 2ada30d8d0f7
    # twitter:
    mail: wuxinoddfuture@126.com


# 百度统计
# 使用博客模板请去掉或者更换 id
baidu:
    id: 7201acde06c1db591b996df4b352f7cd

# Google Analytics
# 使用博客模板请去掉或者更换 id
#ga:
    #id: xxxx
    #host: auto


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》
var sjs = SimpleJekyllSearch({
  searchInput: document.getElementById('search-input'),
  resultsContainer: document.getElementById('results-container'),
  json: '/search.json'
})

var sjs = SimpleJekyllSearch({ ...options })
sjs.search('Hello')

permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 匣子主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}
    - {title: 标签, description: tags, url: '/tags'}
    - {title: 关于沉浸书匣子, description: about, url: '/about'}


# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
